version: "3.9"

services:
  api:
    container_name: api
    build: trng-api/api/
    depends_on:
      - timescaledb
      - trng
  trng:
    container_name: trng
    build: trng-api/trng/
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true # required for gettings access to hardware adapters
    depends_on:
      timescaledb:
        condition: service_healthy
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg16
    env_file:
      - .env
    environment:
      - "POSTGRES_PASSWORD=password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  trng:
    driver: "bridge"