services:
  trng-api:
    container_name: trng-api
    build: .
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true # required for gettings access to hardware adapters
    network_mode: "host"